version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    env_file:
      - ./.env
    ports:
      - 27017:27017
    networks:
      - app-network
    restart: always

  server:
    build: ./server
    container_name: express-api
    environment:
      ATLAS_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_DATABASE}?authSource=admin"
    env_file:
      - ./.env
    ports:
      - 5050:5050
    depends_on:
      - mongo
    networks:
      - app-network
    restart: always

  client:
    build: ./client
    container_name: frontend
    environment:
      - VITE_API_URL=${SERVER_HOST}
    ports:
      - 80:5173
    depends_on:
      - server
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
